### ISSUE TITLE
faceapi.FaceLandmark68TinyNet() bounding boxes?

### ISSUE THREAD

**Issue by hpssjellis** [justadudewhohacks/face-api.js#102]
I just want to say that I really appreciate the work you have put into **face-api.js**. 

I am having a bit of trouble getting things working but I do have a reasonably easy version of faceapi.FaceLandmark68TinyNet() running [here](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/advanced-keras/face/44-face-knn-classifier.html) using the TFJS [knn-classifier](https://github.com/tensorflow/tfjs-models/tree/master/knn-classifier) for face recognition. 

I would like to make my model a bit more accurate by using and showing bounding boxes. From your examples I am not sure if I can stay with the FaceLandmark68TinyNet or if I have to switch to one of the other models (SSD Mobilenet, Tiny Yolo or MTCNN) to get and use the bounding boxes?

**Comment by justadudewhohacks** [comment]
Hmm I think I don't quite understand. Usually you have to detect the bounding boxes before landmark detection, because the landmark net expects the input image to contain roughly only the facial region.

The type of face detector to use depends on your use case. If SSD works for you, stick with it, since it is the most accurate currently. If want to track faces in realtime, for example from a webcam use Tiny Yolo. 

Also soon I will push a new face detecion model, which is faster, smaller and more accurate than the current Tiny Yolo, but not quite as accurate as SSD, though.

**Comment by hpssjellis** [comment]
I will try your new model when you push it. Presently I am having lots of success with this small amount of code. It sounds like it is detecting the bounding boxes I just have to figure out how to layer the boxes onto the video.

 HTML element: (not shown here some basic HTML5 code to activate the webcam)

```
<video  id="myVideo" width="300" height="200" style="border: 1px solid #ddd;"></video>
```
Javascript:
```
   net = new faceapi.FaceLandmark68TinyNet()                                                                               
   await net.load('models/face_landmark_68_tiny_model-weights_manifest.json')                                                                                           
   const img2 = tf.fromPixels(myVideo);                                                                                    
   const myLandmarks = await net.detectLandmarks(img2) 
   
```

**Comment by justadudewhohacks** [comment]
`FaceLandmark68TinyNet` and `FaceLandmark68Net` don't predict bounding boxes first, they predict landmark position straight from the input image. In your case that probably works, because the frames of your video (you are probably using your webcam?) are mostly solely showing the face. 

Stepping back from the camera a bit, you will probably see that the landmarks are not predicted correctly anymore, that's why you usually detect the bounding box first using one of the face detectors.

The library also has utility functions to draw bounding boxes onto a canvas. If you take a look at the examples, I am laying absolutely positioned canvases on top of the html img and video elements.

**Comment by hpssjellis** [comment]
Thanks. I am getting it slowly, the layered canvas makes sense and I do have bounding boxes running using  this code:

```
      result2 = await faceapi.tinyYolov2(videoEl, forwardParams)
      faceapi.drawDetection('overlay', result2.map(det => det.forSize(width, height)))
```

Just going a little slow on using the above information to resize the following code: 

` const myLandmarks = await net.detectLandmarks(img2) `

Not sure how to map the new width and height to the above code.

P.S. Your example code is great I just can't get all of them working. You don't have any live demos anywhere do you?

**Comment by hpssjellis** [comment]
My code is really messy and for some reason I had to use 4 canvases, but I got it working so I can close this issue.  See live demo [here](https://hpssjellis.github.io/beginner-tensorflowjs-examples-in-javascript/advanced-keras/face/backups44-face-drawI.html)  I will be making it better but that demo will work for a while.

Once again. Thanks for getting faceapi.js working with tensorflowjs
