### ISSUE TITLE
Euclidean distance never exceeds 1.0?

### ISSUE THREAD

**Issue by Justin-Maxwell** [justadudewhohacks/face-api.js#173]
Hi.

On the demo website (bbt_face_similarity), I can't find an example where the distance exceeds one.   

I may have my math wrong but would like to understand better.  As I understand it, this means the sum of the squares of the individual distances (presumably many) never exceeds 1.0, otherwise, the sqrt would be >=1 also.  

I'm probably missing something obvious?  Is it just a fluke, or is there something in the math or the data guaranteeing a euclidean difference < 1.0

**Comment by justadudewhohacks** [comment]
Hi,

That might be due to the fact, that each value of a descriptor is usually a small value -1.0 < x < 1.0 (not sure about the exact boundaries here). Thus the distance usually does not exceed 1.0. 

I wouldn't guarantee however, that this is always the case as I understood, the values just happen to lie in that range.
