### ISSUE TITLE
Wanting to add angle detection

### ISSUE THREAD

**Issue by rohanmuplara** [justadudewhohacks/face-api.js#207]
Hi,
I wanted to add angle detection and was possibly hoping to contribute this back to faceapi. I was hoping to see what architecture, couldn't find in the js code, which you have for the 68 keypoint detector that outputs the keypoints.  I wanted to have a net that gives you the landmarks and the angles. If you could also providethe dataset, that would be awesome too.
Thanks,
Rohan

**Comment by justadudewhohacks** [comment]
It is possible to estimate head pose from face landmarks, but it's not implemented yet. The issue for tracking this features is here: #107.

**Comment by rohanmuplara** [comment]
I have been playing around with different architectures, mobilenet,  and you seem to get better results when you train from image to predict angle instead of going from 2d keypoints to angles. This is why I was hoping to to understand what architecture you were using, so I can validate this.

**Comment by justadudewhohacks** [comment]
Ahh sorry. The architecture I used for the face landmark detection net is basically made up by densely connected blocks, which utilize depthwise separable convolutions instead of regular ones. You can find the code for that in the forwardInput method [here](https://github.com/justadudewhohacks/face-api.js/blob/master/src/faceFeatureExtractor/FaceFeatureExtractor.ts#L24-L34) and the corresponding dense block implementation is [here](https://github.com/justadudewhohacks/face-api.js/blob/master/src/faceFeatureExtractor/denseBlock.ts#L30-L55). Basically the FaceFeatureExtractor returns bottleneck features, which you can use and stack your own classifier on top. The face landmark net simply has a fully connected layer stacked on top of the feature extractor, which outputs a vector with entries corresponding to 68 points with x and y coordinates.

**Comment by vihar1996** [comment]
Is it possible to get difference between the face detected is from a image/video or is real human face?
