### ISSUE TITLE
Face Detection Video doesn't work

### ISSUE THREAD

**Issue by mrgoonie** [justadudewhohacks/face-api.js#21]
I checked the Face Detection Video but it doesn't seem to work, there is an error message in the console panel, please see attached screenshot:

![2018-06-26_18-18-35](https://user-images.githubusercontent.com/6857382/41908248-8666c72a-796d-11e8-879c-d72816475acb.png)

Thanks,

**Comment by justadudewhohacks** [comment]
Oops, I think that happens, when the video is loaded before the model is done loading. I will provide a fix for that example.

**Comment by justadudewhohacks** [comment]
Should be fixed now.

**Comment by manishbansal8843** [comment]
@justadudewhohacks I don't think it is still working properly. Although, there is no error in console. But, once the video starts, it recognizes first face and draws the rectangle. After that, as soon as person1(Loenard) moves out of frame, that rectangle sticks to the screen and never moves. PFA the screen shot.
![issue21_face-api](https://user-images.githubusercontent.com/25663886/42147636-5cdd6570-7dec-11e8-8422-278fdef93ad4.png)
![issue21_face-api2](https://user-images.githubusercontent.com/25663886/42147638-607fbf84-7dec-11e8-881a-a7412c0de43c.png)

Is it due to performance issue?
P.S. I have not cloned the repo. I just downloaded the archive from github by clickng download zip button.

**Comment by justadudewhohacks** [comment]
Yes, that's simply because the face detector doesn't run in realtime on your machine.
