### ISSUE TITLE
How to handle exception when face is detected but no descriptor applied?

### ISSUE THREAD

**Issue by Satellite37** [justadudewhohacks/face-api.js#248]
Hi, 

my algorithm gets all faces from the input files at first and saves the faces into a new .jpg like snippets, then i let the user name 1 of them and iterate through the snippets to recognize them and name them and there i got the following exception thrown when there is a face detected but no descriptor.

the .jpg is the snippet generated by the faceapi

```
no faces detected for /mnt/frshare/known/Leanda_1c3c3e487262583a.jpg
(node:6833) UnhandledPromiseRejectionWarning: Error: no faces detected for /mnt/frshare/known/Leanda_1c3c3e487262583a.jpg
    at Promise.all.labels.map (/var/www/html/facereco/face-api.js/examples/examples-nodejs/test.js:290:10)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:6833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6833) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

May you help me with the exception handling please?
I provide the Code as soon as im at home.

Thank you.

**Comment by justadudewhohacks** [comment]
If a face is detected, then there will also be a descriptor. Actually your issue is that there are no faces detected in the image you are using, as the error message suggests.

If you are saving the already cropped and aligned faces images from the API to your disk, then you do not want to perform face detection a second time. In this case you directly want to compute the descriptor of such an image `faceapi.computeFaceDescriptor(img)`. The BBT Face Similarity example does the same.
