### ISSUE TITLE
Detecting face direction or gaze?

### ISSUE THREAD

**Issue by alanrodriguezdotme** [justadudewhohacks/face-api.js#337]
I LOVE this repo. So easy and simple to use. Thanks for this!

I'm looking for a way to detect the direction a face is looking or maybe even gaze detection. Are there any models out there for this that we can just throw into the `weights` folder and play with? Do models need to be converted in a certain way to be used by this API?

**Comment by justadudewhohacks** [comment]
face-api.js does not have a model for gaze detection.

> Do models need to be converted in a certain way to be used by this API?

face-api.js doesn't prescribe or provide an API for custom models. You can simply use tfjs for own models.

**Comment by alanrodriguezdotme** [comment]
Sorry for my basic questions. I'm not very familiar with ML frameworks or TF, so making my own model is beyond my abilities right now.

I'm basically hoping to use something like [OpenVINO's head pose model](https://github.com/opencv/open_model_zoo/blob/master/intel_models/head-pose-estimation-adas-0001/head-pose-estimation-adas-0001.prototxt). I would try to convert it with [this](https://github.com/chaosmail/prototxt-parser).

**Comment by justadudewhohacks** [comment]
Since the model you posted is a .prototxt file, I am assuming that this is a Caffe Model. You can convert tensorflow models to tfjs model using [tfjs-converter](https://github.com/tensorflow/tfjs-converter), but this would require you to convert the Caffe Model to a tensorflow model first. 

Alternatively you can reimplement the network structure described in the .prototxt file with tfjs-core.
