### ISSUE TITLE
Limitations of this api

### ISSUE THREAD

**Issue by Mactacs** [justadudewhohacks/face-api.js#341]
Is there a limit of faces that this api can recognize?

**Comment by justadudewhohacks** [comment]
Not sure if I understood the question correctly. There is no limit, since the face recognition model has been trained to describe the features of a face in form of a 128 dimensional vector, which should be unique to a persons face. Thus you can recognize any face by computing the similarity (euclidean distance) of a face to other faces.

**Comment by Mactacs** [comment]
Thank you for the clarification
