### ISSUE TITLE
best practice for face recognition ?

### ISSUE THREAD

**Issue by one0410** [justadudewhohacks/face-api.js#350]
Hello,
I have some questions?
1. In example, you use 5 sample images for one face. What is the best descriptors size for one face ?  More is better ?

2. Which size is the best aligned image for computing descriptors ? In example, aligned image is 150x150. Should I use larger aligned image ?

Thx.

**Comment by LeonardoDB** [comment]
Hello, I had the same doubts as you.

I did tests with smaller size images, did training with 10 of my images and did not have significant improvements compared to when I trained with only 1 image.

I think an image is enough already.

**Comment by justadudewhohacks** [comment]
> In example, you use 5 sample images for one face. What is the best descriptors size for one face ? More is better ?

Yes you can do that, but usually having one high quality sample image (frontal face image) is enough.

> Which size is the best aligned image for computing descriptors ? In example, aligned image is 150x150. Should I use larger aligned image ?

Using larger input sizes will have no effect, since it will get downscaled to 150x150 anyways. Using smaller sizes will make the input blurry when upscaling, thus the lower the resolution, the less precise the descriptor might be.
