### ISSUE TITLE
Laggy on mobile browsers

### ISSUE THREAD

**Issue by imokya** [justadudewhohacks/face-api.js#416]
the camera example on android browser is slow and laggy. any plan to make the model smaller and faster for mobile browsers?

**Comment by justadudewhohacks** [comment]
Which model are you talking about?

**Comment by imokya** [comment]
> Which model are you talking about?

I tested all three models in the 'webcam face tracking' example，they all appear slow on mobile browers.

**Comment by justadudewhohacks** [comment]
I get ~15 fps on my android phone using the TinyFaceDetector with mobile chrome. It's probably not possible to get much faster than this by creating an even smaller model.

If you need even faster models for mobile devices, maybe you can manage it to train your own TFLite model, but you will have to embedd it into a native android / ios app instead of a web app then.

I am not sure, how much room for optimization in the WebGL backend of tfjs there is remaining to make things run even faster, but I also noticed the tfjs team working on a webgpu backend. Maybe once they release that backend we will see even better performance in browsers.

**Comment by imokya** [comment]
I see. Thanks for your explanation.
