### ISSUE TITLE
Is there a way to convert these models to keras?

### ISSUE THREAD

**Issue by willfu** [justadudewhohacks/face-api.js#484]
Really nice work, impressed by the speed and acuracy. Is there a way to convert these models to keras? I just want to use it in python env. Thanks.

**Comment by justadudewhohacks** [comment]
I basically answered this here: #393. There is no straight forward way to do so. You can of course rebuild the models with tensorflow, then deserialize the weights in a similar way and then convert the tensorflow model to a keras model.

In future models that I am training with tensorflow, I will also upload the .pb file of the trained model so that people can use it with python.

**Comment by willfu** [comment]
ok thanks
