### ISSUE TITLE
How to improve speed of detectSingleFace(video).withFaceLandmarks().withFaceDescriptor() ?

### ISSUE THREAD

**Issue by adumbz** [justadudewhohacks/face-api.js#516]
When loading in browser it takes about 12s to start recognising my face. With some console logging I found the issue to be faceapi.detectSingleFace(video).withFaceLandmarks().withFaceDescriptor(), which takes up most of the time. How can I reduce it to about 3s instead?

```
video.addEventListener('play',()=>{
    const faceMatcher = new faceapi.FaceMatcher(vectors,0.5)
    var idVar = setInterval(async () => {
        const detections2 = await faceapi.detectSingleFace(video).withFaceLandmarks().withFaceDescriptor()
        const results = faceMatcher.findBestMatch(detections2.descriptor) // for detectSingleFace
        if (labels.includes(results['label'])) {
            document.getElementById('msg').innerHTML=(`Hello, ${results['label']}!`)
            clearInterval(idVar)
            // setTimeout(window.close,5000)
    }
    },500)
})
```

**Comment by dalisoft** [comment]
Purchasing good GPU may help (especially NVIDIA good gpu, like GTX 1060). If you using CPU backend, then i don't know, for me 10 fps more than enough on i9-9900K

**Comment by fuadkhalis** [comment]
@adumbz  can i get full your code

**Comment by adumbz** [comment]
I am no longer working on this project so I will close this issue, appreciate your replies @dalisoft @fuadkhalis

**Comment by shriyaaa** [comment]
Hi, I am having the same time issue. Did you manage to make the process faster? Thank you.

**Comment by adamozh** [comment]
Hi @idkidk-idk, sorry for the late reply. I did not manage to do it, suspected it was due to GPU as I was mostly working on my laptop with integrated graphics. I did not notice this issued being raised up much, I would think that this program was built more for a single setup with continuous use, instead of short separate executions. I eventually switched to a paid API with FaceX for conversion and comparison using vectors returned from their API. It was a lot more lightweight as the heavy work was done on their side, and wasn't too expensive for short term projects (7usd per 5000 calls per month). Could get results in about 1-3s depending on your implementation. Hope this helps!
