### ISSUE TITLE
tfjs-core version dependency

### ISSUE THREAD

**Issue by polaroidkidd** [justadudewhohacks/face-api.js#523]
The `README.md` states that 
  > JavaScript face recognition API for the browser and nodejs implemented on top of tensorflow.js core (tensorflow/tfjs-core)

which then links to the recently depricated https://github.com/tensorflow/tfjs-core. Is it still based on this version or the [new tfjs](https://github.com/tensorflow/tfjs)? I've seen some issues where @justadudewhohacks references tfjs-core version 1.4 but I'm not sure.

**Comment by justadudewhohacks** [comment]
I just forgot to update the README with the link to the new repo, thanks for the hint. I try to keep face-api.js updated with the most recent tfjs-core version of course.

> I've seen some issues where @justadudewhohacks references tfjs-core version 1.4 but I'm not sure.

What kind of issue, a common issue is, that people end up with two different versions of tfjs-core, due to another dependency pointing requiring a different tfjs-core version, than the one that face-api.js uses.

**Comment by polaroidkidd** [comment]
>  I try to keep face-api.js updated with the most recent tfjs-core version of course.

Ah, ok. Thanks for clarifying.
 > What kind of issue

I just tried finding some again, but I must habe misread as I can't find any anymore. 
 > a common issue is, that people end up with two different versions of tfjs-core

It appears that this is what I was reading.

**Comment by polaroidkidd** [comment]
Handled in [PR-539](https://github.com/justadudewhohacks/face-api.js/pull/539).
