### ISSUE TITLE
Requirements & Getting started

### ISSUE THREAD

**Issue by jaiminajmeri** [justadudewhohacks/face-api.js#536]
Hey this is really good work. But I would like to suggest you to include requirements with minimum version numbers of dependencies for installing this package and simple getting started check list which ensures all dependencies have been installed correctly. 

I have followed the README.md file steps in order. I was not able to run it one go. Because ts-node npm package was not installed. The guide doesn't specify it either.

Getting started in one go without errors would simply increase the confidence of the user.

**Comment by justadudewhohacks** [comment]
The only dependency of face-api.js is tfjs-core, just make sure you are installing the same tfjs-core version that face-api.js uses (see package.json).

If you are having trouble with typescript then use a typescript version that is compatible with the version this project is compiled with (again see package.json).

> I have followed the README.md file steps in order. I was not able to run it one go. Because ts-node npm package was not installed. The guide doesn't specify it either.

Using tools such as ts-node or typescript is not a requirement in order to use face-api.js and I think it should be self explanatory that you have to install it first in order to use such a tool.

**Comment by jaiminajmeri** [comment]
@justadudewhohacks, thanks for explaining. New to node.js. learnt a thing today.
I thought Node.js handles typescript just like we do `node myscript.js` way.
