### ISSUE TITLE
Conflict when using Tensorflow.js with face-api.js

### ISSUE THREAD

**Issue by joshnewnham** [justadudewhohacks/face-api.js#61]
I'm working on a prototype where I need to use tensorflow.js (load the models); there seems to be a conflict between the namespace with your version (assume you're just using core) and the official. I need access to, at least, loadModel which is not available in your module. I've tried importing both but only the first one assigns itself to the globally.

**Comment by justadudewhohacks** [comment]
Yes face-api.js only uses tfjs-core. What do you mean by namespace collision? This module doesn't export tf on the global scope, so there shouldn't be any collisions.

**Comment by immortal3** [comment]
Importing tensor-flow like this creating error in namespace and causing problems. **(Noob in JS)**
Can you have solution to import only once.
```
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@0.12.0"> </script>
```

**Comment by justadudewhohacks** [comment]
I see what the issue is, apparently tf can't register the WebGL backend twice.

Anyways, I wouldn't include both scripts like that anyways. Just install both modules via npm and bundle them together.

**Comment by justadudewhohacks** [comment]
Now I see what the actual issue was here.

In version 0.12.0 I bumped the tfjs-core version to latest (0.12.14), which includes the fix (last PR referenced in [this](https://github.com/tensorflow/tfjs/issues/109) issue), which allows tfjs to reuse a backend instead of registering it again, if it has already been registered from another script. 

If there are still issue, feel free to reopen.

**Comment by aPToul** [comment]
@joshnewnham  did you ever find a solution to this?
