### ISSUE TITLE
Browser faster then node.

### ISSUE THREAD

**Issue by MacMillan13** [justadudewhohacks/face-api.js#694]
faceExpressionRecognition faster in the browser than on the node. How to fix it?

**Comment by MacMillan13** [comment]
![Screenshot from 2020-09-17 14-29-18](https://user-images.githubusercontent.com/18086617/93465548-a0fe8e80-f8f3-11ea-9fc1-1fd51368199e.png)
Also, I have some messages before the script of js start.

**Comment by vladmandic** [comment]
messages are normal, they are coming from `tfjs-node` package when it's loading.

regarding performance, are you using `tfjs-node` or `tfjs-node-gpu` with `cuda`-enabled acceleration?  
if you want to get GPU acceleration that you have by default in you browser via WebGL, you need to use `tfjs-node-gpu` and must have `cuda` installed - otherwise its running on CPU and it's definitely much slower.
