### ISSUE TITLE
TypeError: t.toFloat is not a function TensorFlow with React

### ISSUE THREAD

**Issue by vishaldhull09** [justadudewhohacks/face-api.js#794]
trying to run face-api.js on react app

NetInput.js:139 Uncaught (in promise) TypeError: t.toFloat is not a function
    at NetInput.js:139
    at Array.map (<anonymous>)
    at NetInput.js:139
    at engine.js:327
    at Engine.scopedRun (engine.js:337)
    at Engine.tidy (engine.js:326)
    at Module.tidy (globals.js:175)
    at NetInput../face-api.js/node_modules/tfjs-image-recognition-base/build/es6/dom/NetInput.js.NetInput.toBatchTensor (NetInput.js:123)
    at SsdMobilenetv1.ts:30
    at engine.js:327

**Comment by vladmandic** [comment]
`* is not a function` for any tensorflow function pretty much always comes down to tensorflow backend not registered correctly. which again comes down to multiple incompatible versions of tensorflow being used.  

if you're using `tfjs` 2.x or 3.x, you'll end up with this because original `face-api` has not not been updated for a long time and includes embedded `tfjs` v1 which is NOT compatible with tfjs 2.x or tfjs 3.x.

that's main reason why this port exists: <https://github.com/vladmandic/face-api>
