### ISSUE TITLE
euclidean distance 

### ISSUE THREAD

**Issue by hemcodemode** [justadudewhohacks/face-api.js#86]
Euclidean distance never goes down below 0.4. What is the ideal number of picture of one person to train the model. Can we implement svm or multiclass classification here ?

**Comment by hemcodemode** [comment]
O.4 is the distance therefore confidence is 1-0.4 = 0.6, so i am saying that why this confidence not going beyond 0.6 or 0.65 even with the 5 pictures of same person ? Since i have implemented face recognition in Python using dlib which is giving confidence upto 0.98. Also there is quit differences between dlibs face encoding of python based dlib model and this face-api.js based dlib model although they are of same dimensions which is 128
Thanks

**Comment by justadudewhohacks** [comment]
`confidence is 1-0.4 = 0.6` I don't think you can directly translate the distance metric to confidence score like that.

Are you using an intel GPU? The model should be the same as the dlib one, maybe there are some minor difference due to weight quantization. Actually I didn't see that large of difference between the python model and the model exposed here, maybe one would have to investigate this closer with a larger benchmark.

**Comment by yaganalldoctors** [comment]
@justadudewhohacks 

> confidence is 1-0.4 = 0.6 I don't think you can directly translate the distance metric to confidence score like that.

If this is not the best way to calculate confidence score (%) in recognition, what would be the best way?

**Comment by justadudewhohacks** [comment]
There is not really a way to calculate a confidence score. The lower the distance the more similar two faces are. A distance lower than 0.6 means, that the faces are very likely from the same person.
